"""L3 -- the council memo (COOLBLOCK-BUILD-PLAN.md §7.1 L3): "a formatted
2-page document: executive summary, methodology note, equity statement,
site table, citations to the 5 papers" -- generated by Claude against a
strictly real, computed payload, verified by L6's provenance guard
(`engine.narrate.provenance`).

**Citations, scoped honestly.** The plan's own D16 (`engine/ingest/d16_literature.py`)
already registers the five papers' real titles/venues/DOIs and *what each
one is used for* -- curated by hand, not retrieved. §7.1 L3 additionally
asks for retrieval "via pgvector retrieval," which D16's own docstring
already defers to Phase 10 ("the chunk/embed pipeline are Phase 10 work,
not automatable ingest"). At five documents, handing the model the whole
curated list directly is more reliable than a semantic-search step over a
five-row corpus would be -- retrieval solves a scale problem this corpus
doesn't have. Building the embed/pgvector pipeline remains open, tracked
here rather than silently skipped.

**The honesty rail, enforced in the prompt, not just in the data.**
`docs/METHODOLOGY.md`'s heat-surface validation gate did not clear all
three checks (2 of 3) -- per §1.4, the product's language must say
"prioritization score," never "predicted cooling," wherever the heat
surface or the cooling kernel's degree estimates are discussed. That rule
lives in `SYSTEM_PROMPT` below, not left to the model to infer, and
`METHODOLOGY_FACTS` gives it the real, current validation numbers to cite
if it wants to explain *why*.
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

import anthropic
from dotenv import load_dotenv

from engine.narrate.provenance import NumberMatch, verify_numbers

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
CITATIONS_PATH = REPO_ROOT / "data" / "cache" / "literature" / "2026-09-04" / "citations.json"

MEMO_MODEL = "claude-opus-5"  # quality, run once (§7.1 model routing) -- claude-sonnet-5 is the interactive/L1/L2 model
MAX_OUTPUT_TOKENS = 2200

# Kept in sync by hand with docs/METHODOLOGY.md -- last verified 2026-09-08.
# A parser over that document would be more automatic and more fragile;
# this is exactly the small, fixed set of numbers the memo is allowed to
# cite about the model's own validation status, so a manually-reviewed
# constant is the more honest choice here, not a shortcut around one.
METHODOLOGY_FACTS = {
    "heat_surface_validation_checks_passed": 2,
    "heat_surface_validation_checks_total": 3,
    "heat_surface_downscaling_r2_spatial_cv": 0.215,
    "heat_surface_downscaling_rmse_degc": 0.94,
    "cooling_kernel_beta_degc_per_canopy_fraction_increment": -6.95,
    "cooling_kernel_r2": 0.073,
}

SYSTEM_PROMPT = """You are drafting a council memo for a city sustainability office and a \
neighborhood association board deciding how to spend a real heat-mitigation grant. The reader is a \
city council member or planner, not a data scientist -- write in plain, direct prose.

You will be given a JSON payload of real, already-computed data. Follow these rules exactly:

1. Every number you state must come directly from the JSON payload (including its "methodology" \
   section). Do not compute new derived statistics beyond what is already in the payload, and do \
   not round or approximate numbers away from what is given.
2. The heat-surface validation gate did NOT pass all three of its checks (see \
   "heat_surface_validation_checks_passed" / "_total" in the payload). Per this project's honesty \
   rail, you must call cooling estimates a "prioritization score," never "predicted cooling" or a \
   guaranteed outcome -- use words like "modeled" or "estimated," and if you discuss degrees of \
   cooling, note plainly that the underlying temperature model is a prioritization tool, not a \
   validated forecast.
3. Cite only the papers and city plans listed in the payload's "citations" field. Do not invent or \
   embellish titles, authors, venues, or findings beyond what "used_for" already states.
4. Write plain text only -- no markdown headers, bold, italics, or bullet-point characters. Use \
   section labels in ALL CAPS on their own line, with a blank line before and after each one.
5. Sections, in this order: EXECUTIVE SUMMARY, SITE SELECTION AND ALLOCATION, EQUITY STATEMENT, \
   METHODOLOGY AND LIMITATIONS, HOW THIS COMPARES TO OTHER APPROACHES (only if the payload includes \
   "baseline_comparison"; omit this section entirely otherwise), SOURCES (list each citation's title \
   and venue/publisher).
6. Target 500-800 words total. Do not pad with generic filler about climate change in general --
   every sentence should trace to something in the payload.
"""


def load_citations() -> dict[str, list[dict[str, Any]]]:
    if not CITATIONS_PATH.exists():
        return {"papers": [], "city_plans": []}
    data: dict[str, list[dict[str, Any]]] = json.loads(CITATIONS_PATH.read_text(encoding="utf-8"))
    return data


def build_memo_payload(
    *,
    neighborhood_name: str,
    city: str,
    state: str,
    plan_name: str,
    budget_usd: float,
    solver: str,
    sites: list[dict[str, Any]],
    total_cost_usd: float,
    total_ewcb: float,
    baseline_comparison: dict[str, float] | None = None,
) -> dict[str, Any]:
    """Assembles the exact JSON the model sees, computing every derived
    statistic (per-site average, % of budget used, per-intervention-type
    counts, baseline uplift) here rather than trusting the model to do
    arithmetic in its own generation -- both more accurate, and it means
    L6's provenance guard has a real payload number to match a stated
    derived figure against, instead of flagging every reasonable ratio
    the model states as unverifiable."""
    n_sites = len(sites)
    intervention_counts: dict[str, int] = {}
    for site in sites:
        intervention_counts[site["intervention_type"]] = intervention_counts.get(site["intervention_type"], 0) + 1

    payload: dict[str, Any] = {
        "neighborhood_name": neighborhood_name,
        "city": city,
        "state": state,
        "plan_name": plan_name,
        "budget_usd": budget_usd,
        "solver": solver,
        "n_sites": n_sites,
        "total_cost_usd": total_cost_usd,
        "total_ewcb_person_degree_hours": total_ewcb,
        "avg_cost_per_site_usd": (total_cost_usd / n_sites) if n_sites else 0.0,
        "pct_of_budget_used": (total_cost_usd / budget_usd * 100) if budget_usd else 0.0,
        "intervention_type_counts": intervention_counts,
        "top_sites_by_marginal_ewcb": sorted(sites, key=lambda s: -s["marginal_gain_ewcb"])[:10],
        "methodology": METHODOLOGY_FACTS,
        "citations": load_citations(),
    }

    if baseline_comparison:
        others = {k: v for k, v in baseline_comparison.items() if k != "coolblock"}
        best_other_name = max(others, key=lambda k: others[k]) if others else None
        best_other_value = others.get(best_other_name, 0.0) if best_other_name else 0.0
        coolblock_value = baseline_comparison.get("coolblock", 0.0)
        payload["baseline_comparison"] = baseline_comparison
        if best_other_name and best_other_value > 0:
            payload["best_other_strategy_name"] = best_other_name
            payload["coolblock_uplift_multiple_over_best_other"] = round(coolblock_value / best_other_value, 2)

    return payload


@dataclass(frozen=True)
class MemoResult:
    text: str
    numbers: list[NumberMatch] = field(default_factory=list)
    unverified_count: int = 0
    regenerated: bool = False


def _extract_text(response: anthropic.types.Message) -> str:
    return "".join(block.text for block in response.content if block.type == "text")


def generate_council_memo(payload: dict[str, Any], *, client: anthropic.Anthropic | None = None) -> MemoResult:
    """Generates the memo, then runs L6's provenance guard. If any number
    fails to verify, regenerates exactly once with a corrective note
    naming the offending numbers (§7.1 L6: "Unmatched numbers trigger a
    flagged regeneration"); if numbers still fail after that, they are
    returned unverified rather than silently dropped or retried forever
    ("persistent failures are surfaced to the user")."""
    load_dotenv()  # ANTHROPIC_API_KEY lives in the repo root .env, same pattern as engine/ingest/d07_census.py
    client = client or anthropic.Anthropic()
    user_message = (
        "Here is the real, already-computed data for this plan. Use only these numbers.\n\n"
        + json.dumps(payload, indent=2, default=str)
    )

    def _call(extra_system: str = "") -> str:
        response = client.messages.create(
            model=MEMO_MODEL,
            max_tokens=MAX_OUTPUT_TOKENS,
            system=SYSTEM_PROMPT + extra_system,
            messages=[{"role": "user", "content": user_message}],
        )
        return _extract_text(response)

    text = _call()
    numbers = verify_numbers(text, payload)
    unverified = [n for n in numbers if not n.verified]
    regenerated = False

    if unverified:
        offending = ", ".join(sorted({n.raw for n in unverified}))
        correction = (
            f"\n\nYour previous draft included these numbers, which do not match anything in the "
            f"provided data: {offending}. Rewrite the entire memo using ONLY numbers that appear in "
            f"the JSON payload above."
        )
        text = _call(correction)
        numbers = verify_numbers(text, payload)
        unverified = [n for n in numbers if not n.verified]
        regenerated = True

    return MemoResult(text=text, numbers=numbers, unverified_count=len(unverified), regenerated=regenerated)
