"""initial schema: workspaces, plans, scenarios, sites, share links, annotations, audit log

Revision ID: 01ebcca4db1f
Revises: 
Create Date: 2026-09-08 00:11:34.783123

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from geoalchemy2 import Geometry
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '01ebcca4db1f'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workspaces',
    sa.Column('id', sa.String(length=200), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.String(length=200), nullable=False),
    sa.Column('user_id', sa.String(length=200), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=False),
    sa.Column('target_id', sa.String(length=200), nullable=False),
    sa.Column('extra', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_workspace_id'), 'audit_log', ['workspace_id'], unique=False)
    op.create_table('plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.String(length=200), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('budget_usd', sa.Float(), nullable=False),
    sa.Column('constraints', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plans_workspace_id'), 'plans', ['workspace_id'], unique=False)
    op.create_table('workspace_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.String(length=200), nullable=False),
    sa.Column('user_id', sa.String(length=200), nullable=False),
    sa.Column('role', sa.Enum('owner', 'editor', 'viewer', name='workspace_role'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'user_id', name='uq_workspace_member')
    )
    op.create_table('annotations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('author_user_id', sa.String(length=200), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_annotations_plan_id'), 'annotations', ['plan_id'], unique=False)
    op.create_table('scenario_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'done', 'error', name='scenario_status'), nullable=False),
    sa.Column('solver', sa.String(length=50), nullable=True),
    sa.Column('objective_value_ewcb', sa.Float(), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('job_id', sa.String(length=200), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_id', 'version_number', name='uq_plan_version_number')
    )
    op.create_index(op.f('ix_scenario_versions_plan_id'), 'scenario_versions', ['plan_id'], unique=False)
    op.create_table('scenario_sites',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scenario_version_id', sa.UUID(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.String(length=100), nullable=False),
    sa.Column('intervention_type', sa.String(length=50), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('marginal_gain_ewcb', sa.Float(), nullable=False),
    sa.Column('cumulative_ewcb', sa.Float(), nullable=False),
    sa.Column('cumulative_cost_usd', sa.Float(), nullable=False),
    sa.Column('geometry', Geometry(geometry_type='POLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('properties', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['scenario_version_id'], ['scenario_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # No explicit `idx_scenario_sites_geometry` GIST index here: GeoAlchemy2
    # creates it automatically via a DDL event on `create_table` for any
    # `Geometry(..., spatial_index=True)` column (the default) -- adding it
    # again here would double-create it (`DuplicateTable`).
    op.create_index(op.f('ix_scenario_sites_scenario_version_id'), 'scenario_sites', ['scenario_version_id'], unique=False)
    op.create_table('share_links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scenario_version_id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['scenario_version_id'], ['scenario_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_share_links_scenario_version_id'), 'share_links', ['scenario_version_id'], unique=False)
    op.create_index(op.f('ix_share_links_token'), 'share_links', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_share_links_token'), table_name='share_links')
    op.drop_index(op.f('ix_share_links_scenario_version_id'), table_name='share_links')
    op.drop_table('share_links')
    op.drop_index(op.f('ix_scenario_sites_scenario_version_id'), table_name='scenario_sites')
    op.drop_table('scenario_sites')  # drops the GeoAlchemy2-managed GIST index along with the table
    op.drop_index(op.f('ix_scenario_versions_plan_id'), table_name='scenario_versions')
    op.drop_table('scenario_versions')
    op.drop_index(op.f('ix_annotations_plan_id'), table_name='annotations')
    op.drop_table('annotations')
    op.drop_table('workspace_members')
    op.drop_index(op.f('ix_plans_workspace_id'), table_name='plans')
    op.drop_table('plans')
    op.drop_index(op.f('ix_audit_log_workspace_id'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_table('workspaces')
    # ### end Alembic commands ###
    # Alembic's Postgres ENUM autogeneration creates the type as a side
    # effect of the first column that uses it, but never drops it on
    # downgrade -- without this, downgrading and re-upgrading fails on
    # "type already exists".
    sa.Enum(name='scenario_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='workspace_role').drop(op.get_bind(), checkfirst=True)
